//Layout file: Everything in here remains across all the pages of the app (e.g. headers and footers)

import type { Metadata } from "next";
import Footer from "../components/Footer";
import Navbar from "../components/Navbar";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import 'react-datepicker/dist/react-datepicker.css';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Tradeable Invoice App",  //title as seen in the tab
  description: "Generated by create next app", //
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[url(/image/try.png)]` } >
        <main>
          <Navbar/>
          {children} 
        </main>
        <Footer/>
      </body>
    </html>
  );
}
